language: generic
sudo: required

services:
    - docker

before_install:
    - docker build -t kviev/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true kviev/react-test npm test

after_success:
    - docker build -t kviev/multi-client -f ./client
    - docker build -t kviev/multi-nginx -f ./nginx
    - docker build -t kviev/multi-server -f ./server
    - docker build -t kviev/multi-worker -f ./worker
    
    #Log in to docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    #Take those images and push them tp docker hun
    - docker push kviev/mult-client
    - docker push kviev/mult-nginx
    - docker push kviev/mult-server
    - docker push kviev/mult-worker



